python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_E3k_UniVar_96_192 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features S \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --itr 3 \
  --learning_rate 0.0001 \
  --d_model 256 \
  --dropout 0.01 \
  --anomaly 1.0 \
  --fix_seed 2023 \
  --checkpoints ./checkpoints1/


python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_E3k_UniVar_96_336 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features S \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --itr 3 \
  --learning_rate 0.0001 \
  --d_model 256 \
  --dropout 0.01 \
  --anomaly 1.0 \
  --fix_seed 2023 \
  --checkpoints ./checkpoints2/


python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_E3k_UniVar_96_720 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features S \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --itr 3 \
  --learning_rate 0.0001 \
  --d_model 256 \
  --dropout 0.01 \
  --anomaly 1.0 \
  --fix_seed 2023 \
  --checkpoints ./checkpoints1/