python -u run_singlemodU2.py \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_E3k_Singlemod_96_720 \
  --model B6autoformer \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --itr 1 \
  --learning_rate 0.001 \
  --dropout 0.1 \
  --fix_seed 2023 \
  --checkpoints ./checkpoints3/