python -u run_dualmodb.py \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_MantraB_96_336 \
  --model Mantra \
  --slow_model MantraB \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --n_learner 10 \
  --urt_heads 7 \
  --itr 3 \
  --fix_seed 2021,2022,2023 \
  --checkpoints ./checkpoints3/