python -u run_dualmodb.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id MantraB_ECL_96_720 \
  --model Mantra \
  --slow_model MantraB \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --train_epochs 20 \
  --n_learner 10 \
  --urt_heads 7 \
  --itr 3 \
  --fix_seed 2021,2022,2023 \
  --checkpoints ./checkpoints3/