python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id E3k_ECL_96_96 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 1 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --train_epochs 20 \
  --n_learner 3 \
  --urt_heads 1 \
  --learning_rate 0.0001 \
  --dropout 0.2 \
  --d_model 256 \
  --itr 3 \
  --fix_seed 2023 \
  --checkpoints ./checkpoints0/

python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id E3k_ECL_96_192 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 1 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --train_epochs 20 \
  --n_learner 3 \
  --urt_heads 1 \
  --learning_rate 0.0001 \
  --dropout 0.2 \
  --d_model 256 \
  --itr 3 \
  --fix_seed 2023 \
  --checkpoints ./checkpoints1/


python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id E3k_ECL_96_336 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 1 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --train_epochs 20 \
  --n_learner 3 \
  --urt_heads 1 \
  --learning_rate 0.0001 \
  --dropout 0.2 \
  --d_model 256 \
  --itr 3 \
  --fix_seed 2023 \
  --checkpoints ./checkpoints3/