python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_E3k_UniVar_36_24 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features S \
  --seq_len 36 \
  --label_len 18 \
  --pred_len 24 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --learning_rate 0.001 \
  --dropout 0.2 \
  --d_model 256 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 20 \
  --batch_size 32 \
  --checkpoints ./checkpoints0/


python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_E3k_UniVar_36_36 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features S \
  --seq_len 36 \
  --label_len 18 \
  --pred_len 36 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --learning_rate 0.001 \
  --dropout 0.2 \
  --d_model 256 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 20 \
  --batch_size 32 \
  --checkpoints ./checkpoints1/



python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_E3k_UniVar_36_48 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features S \
  --seq_len 36 \
  --label_len 18 \
  --pred_len 48 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --learning_rate 0.001 \
  --dropout 0.2 \
  --d_model 256 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 20 \
  --batch_size 32 \
  --checkpoints ./checkpoints2/


python -u run_dualmode3k.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_E3k_UniVar_36_60 \
  --model B6autoformer \
  --slow_model AutoformerS1 \
  --data custom \
  --features S \
  --seq_len 36 \
  --label_len 18 \
  --pred_len 60 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --n_learner 3 \
  --urt_heads 1 \
  --learning_rate 0.001 \
  --dropout 0.2 \
  --d_model 256 \
  --itr 3 \
  --fix_seed 2023 \
  --train_epochs 20 \
  --batch_size 32 \
  --checkpoints ./checkpoints3/
